# Generated by Django 5.0 on 2023-12-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Devs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("designation", models.CharField(max_length=128)),
                ("organisation", models.CharField(max_length=128)),
                ("address", models.TextField(max_length=512)),
                ("city", models.CharField(max_length=64)),
                ("state", models.CharField(max_length=64)),
                ("country", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=128)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("updated_by", models.CharField(max_length=128)),
            ],
        ),
    ]
