# Generated by Django 5.0 on 2023-12-11 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Devs",
            new_name="Dev",
        ),
    ]
