# Generated by Django 5.0 on 2023-12-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_rename_devs_dev"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dev",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="dev",
            name="created_by",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="dev",
            name="updated_by",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
